## Basic Configuration

baseurl = "/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Yixi Zhang"
title = "Yixi Zhang"

theme = "hugo-goa"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Yixi Zhang"
intro = "I write code at startup"
description = "Previously <a href='https://www.woven.com'>Woven</a>, <a href='https://www.memsql.com'>MemSQL</a> and <a href='https://www.facebook.com'>Facebook</a>."
authorimage = "headshot.jpg"
dateformat = "April 15, 2012"

## Site Meta Settings
[params.meta]
description = "hack and life"
keywords = "minimalist,developer"

## Social Accounts
[params.social]
github = "yixizhang"
linkedin = "yixizhang"
twitter = "yixiza"

## Extras
[params.extra]
copyright = "© 2019. Yixi Zhang."
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
